# Generated by Django 3.2.16 on 2023-08-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='minioObjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Minio file path')),
                ('bucket_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bucket name')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='File size')),
            ],
            options={
                'verbose_name_plural': 'Bucket object list',
            },
        ),
    ]
