# Generated by Django 3.2.16 on 2023-08-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_geoviz', '0002_alter_minioobjectlist_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='minioobjectlist',
            name='file_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='File name'),
        ),
    ]
