# Generated by Django 3.2.16 on 2023-10-09 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geonode_geoviz', '0004_delete_minioobjectlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='seabee_otter_mission',
            fields=[
                ('mission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Mission Id')),
                ('location_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Location name')),
                ('project_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Project name')),
                ('mission_date', models.DateField(blank=True, null=True, verbose_name='Mission date')),
                ('latitude', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('logitude', models.IntegerField(blank=True, null=True, verbose_name='Logitude')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name_plural': 'Seabee Otter mission',
            },
        ),
        migrations.CreateModel(
            name='Historicalseabee_otter_mission',
            fields=[
                ('mission_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Mission Id')),
                ('location_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Location name')),
                ('project_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Project name')),
                ('mission_date', models.DateField(blank=True, null=True, verbose_name='Mission date')),
                ('latitude', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('logitude', models.IntegerField(blank=True, null=True, verbose_name='Logitude')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical seabee_otter_mission',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
