# Generated by Django 3.2.16 on 2023-10-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_geoviz', '0005_historicalseabee_otter_mission_seabee_otter_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseabee_otter_mission',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='historicalseabee_otter_mission',
            name='logitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Logitude'),
        ),
        migrations.AlterField(
            model_name='seabee_otter_mission',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='seabee_otter_mission',
            name='logitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Logitude'),
        ),
    ]
