# Generated by Django 3.2.16 on 2023-10-17 08:37

from django.db import migrations, models
import django_minio_backend.models
import functools
import geonode.dmc.models


class Migration(migrations.Migration):

    dependencies = [
        ('geonode_dmc', '0002_auto_20231009_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddc_upload',
            name='configyaml',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='geoviz-upload-data'), upload_to=functools.partial(geonode.dmc.models.get_upload_path, *(), **{'folder': ''}), verbose_name='Upload NodeODM config file as .yaml'),
        ),
        migrations.AddField(
            model_name='historicalddc_upload',
            name='configyaml',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Upload NodeODM config file as .yaml'),
        ),
    ]
